import React from 'react';

const DashboardHome = () => {
    return (
        <div>
            <h4>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum, quod dolores, ab dolore dignissimos similique placeat sed porro ea perspiciatis veniam ut ullam iure, reprehenderit rerum hic. Voluptates similique ipsam quae aliquam nam, at distinctio, voluptate beatae vero laudantium placeat corporis fugit velit alias dolorum odit facere magni modi ea tempore, commodi possimus unde. Ea ab natus obcaecati similique quibusdam, ullam facere officia ipsa sequi! Et consectetur, corporis voluptate odit inventore, consequatur assumenda ullam quos ad, a tenetur delectus illum dolorum optio minus debitis perspiciatis exercitationem sequi eum molestias excepturi. Ratione reiciendis numquam quidem laborum fugiat tenetur voluptas! Cupiditate iure porro tempora deleniti maxime at, facere accusamus cum doloribus vero dolores, impedit accusantium eligendi fuga aperiam quaerat hic. Nam quia aliquam voluptas porro ipsum consectetur dolorum mollitia. Recusandae voluptate, necessitatibus labore sit nobis, eos ut maiores suscipit nulla magni deleniti quis. Accusamus totam itaque voluptatum laudantium ad sequi vero velit, enim, odio non aperiam dolorem temporibus? Vero omnis deleniti, natus tenetur maiores perspiciatis quam excepturi? Doloribus reiciendis maxime qui. Nihil nam, expedita ducimus ipsam aliquam illo corrupti quaerat. Dicta modi qui inventore dignissimos obcaecati illo, quia ducimus iure, veniam placeat accusamus dolorem nostrum soluta at doloremque nemo quod et ratione odit commodi. Veritatis hic iure debitis accusantium odit laborum ratione consequatur error excepturi saepe, totam architecto aliquam quos officiis, accusamus libero nemo. Recusandae repudiandae ipsum atque explicabo numquam obcaecati accusamus optio? Rem quibusdam aspernatur, corrupti culpa et velit omnis earum consequuntur dolorem sit fugiat reiciendis alias libero expedita atque non!</h4>
        </div>
    );
};

export default DashboardHome;